### ISSUE TITLE
CF push should fail if nginx version is not supported by OneAgent

### ISSUE THREAD

**Issue by TimGerlach** [Dynatrace/libbuildpack-dynatrace#32]
### Problem Statement
At SAP we're using the [nginx buildpack](https://github.com/cloudfoundry/nginx-buildpack/) to instrument nginx apps on Cloud Foundry with Dynatrace. We noticed that if a new nginx version is used in the nginx buildpack which is not yet [supported by the Dynatrace OneAgent](https://docs.dynatrace.com/docs/setup-and-configuration/technology-support/application-software/nginx#nginx-versions) `cf push` still succeeds giving a false sense of security that 'everything' worked well. It only becomes visible in the Dynatrace UI as the nginx app does not show up.

### Desired Solution
It would be more "Cloud Foundry-native" if the staging of the app fails when the Dynatrace OneAgent cannot support the nginx version used by the buildpack. This way stakeholders would immediately know that the contract they have with Cloud Foundry through the manifest file (nginx buildpack + bound dynatrace service) cannot be fulfilled and an action is required. Ideally the staging would fail with a descriptive error message by the libbuildpack-dynatrace hook explaining that this version of nginx is not supported and how to pin to an older version of nginx.

**Comment by arthfl** [comment]
Ahoy Tim, long time no see :-)

This might be hard to achieve and maybe even unwanted by some. We usually do our best to not fail application deployments if there is an issue with the agent injection. Because then you at least have your systems running, although it is not fully monitored.

But i'll discuss this internally and keep you updated.

**Comment by TimGerlach** [comment]
Hi @arthfl ,
Thank you for the swift response. I think the [`skipErrors`](https://github.com/Dynatrace/libbuildpack-dynatrace/blob/master/hook.go#L34) flag controls whether the buildpack staging phase should continue even if there are errors. By default it is `false` meaning that with the current implementation it should already fail if it's unable to do what was requested and stakeholders can set the flag to `true` in case they'd like to continue without Dynatrace.

Thanks for discussing this internally. It'd be great if there's anything that can be improved to make it more transparent to the user that they're running without the Dynatrace instrumentation.

**Comment by arthfl** [comment]
We can't fulfill this request.

In the buildpack integration we just prepare everything and setting up the environment. The actual injection for monitoring happens during the apps startup, which is outside of the reach of the integration.
Also checked internally and we *intentionally* do absolutly not crash anything if the injection is not working for whatever reasons. Because having apps running without monitoring is still better than apps crashing without monitoring.
